#!/bin/ksh
#SBATCH --job-name=OPP
#SBATCH -p shared
#SBATCH --time=08:00:00
#SBATCH -A ba1035

e=$1
start=$2
end=$3
res=$4
var=$5
dir=$6

for i in {${start}..${end}}
do
	filelist+="/p/largedata/hhb19/jstreffi/runtime/oifsamip/MILES/files/Block/${res}_$(printf "%03g" ${i})/${e}/2001_2001/DJFM/D12_Clim_${res}_$(printf "%03g" ${i})_${e}_2001_2001_DJFM.nc "
done
cd /p/largedata/hhb19/jstreffi/runtime/oifsamip/MILES/files/Block
cdo ensmean $filelist D12_Clim_T${res}_ensmean_${e}_2001_2001_DJFM.nc

