#! /bin/bash
set -x



cd /mnt/lustre01/work/ba1035/a270092/postprocessing/PAMIP
#p1=11  ii=12  si=13  ai=15  af=16 
var="z500"
string=ensmean_50000Pa
exp1=$1
exp2=$2

for season in DJF MAM JJA SON
do
  cdo ensmean T63_${var}_${season}_${exp1}-${exp2}_${string}.nc T127_${var}_${season}_${exp1}-${exp2}_${string}.nc T159_${var}_${season}_${exp1}-${exp2}_${string}.nc T511_${var}_${season}_${exp1}-${exp2}_${string}.nc mmm_${var}_${season}_${exp1}-${exp2}_${string}.nc
done
exit 0

